FROM thake/logminer-connect:6.0.1-5.5.1

ADD https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/19.7.0.0/ojdbc8-19.7.0.0.jar /usr/share/confluent-hub-components/thake-logminer-kafka-connect/lib